version: '2.0'
services:

  node:
    image: parity/parity:${PARITY_VERSION}
    command:
      --config /parity/config/authority.toml
      --nat extip:${EXTERNAL_IP}
      --gas-floor-target 8000000
    volumes:
      - ./config:/parity/config:ro
      - ./chain:/root/.local/share/io.parity.ethereum/
      - ./.secret:/parity/authority.pwd:ro
    ports:
      - 30303:30303 
      - 30303:30303/udp